const people = [
  {
    id: 1,
    image: '/person0.png',
    name: 'Samantha Parker',
    title: 'Registered Nurse',
    quote:
      'The HeartBeat has revolutionized the way I find nursing job opportunities, making it seamless and efficien.',
  },
  {
    id: 2,
    image: '/person1.png',
    name: 'Sarah Ramirez',
    title: 'Pediatric Nurse',
    quote:
      'Mapping functionality on The HeartBeat has made it incredibly easy for me to locate nearby job opportunities and plan my work schedule effectively.',
  },
  {
    id: 3,
    image: '/person2.png',
    name: 'Emily Chen',
    title: 'Oncology Nurse',
    quote:
      'The HeartBeat provides a user-friendly platform with a seamless authentication experience, making it convenient to access job opportunities.',
  },
  {
    id: 4,
    image: '/person3.png',
    name: 'Michael Collins',
    title: 'Critical Care Nurse',
    quote:
      'Real-time chat feature on The HeartBeat has greatly improved communication between nurses and employers, facilitating smooth collaboration. ',
  },
];

const jobs = [
  {
    "id": "1",
    "category": "Nursing",
    "year_required": 5,
    "title": "Senior Nurse",
    "employer": "123",
    "assignTo": null,
    "approve": false,
    "completed": false,
    "location": "New York, NY",
    "startDate": "2023-07-01",
    "endDate": "2023-07-31",
    "M": true,
    "T": true,
    "W": false,
    "Th": true,
    "F": true,
    "St": false,
    "Sn": false,
    "start": "09:00:00",
    "end": "17:00:00",
    "shiftHour": 8,
    "patient_population": "adults",
    "patient_number": 15,
    "stipend": 2000,
    "weekly_pay": 1000,
    "bonus": 500,
    "contact_person": "John Doe",
    "contact_email": "john.doe@example.com",
    "parkingFree": true,
    "additionalDetails": "N/A"
  },
  {
    "id": "2",
    "category": "Paediatrics",
    "year_required": 3,
    "title": "Children's Nurse",
    "employer": "789",
    "assignTo": null,
    "approve": false,
    "completed": false,
    "location": "Los Angeles, CA",
    "startDate": "2023-07-10",
    "endDate": "2023-08-10",
    "M": true,
    "T": true,
    "W": true,
    "Th": false,
    "F": false,
    "St": false,
    "Sn": true,
    "start": "09:00:00",
    "end": "18:00:00",
    "shiftHour": 9,
    "patient_population": "children",
    "patient_number": 10,
    "stipend": 1500,
    "weekly_pay": 800,
    "bonus": 300,
    "contact_person": "Jane Doe",
    "contact_email": "jane.doe@example.com",
    "parkingFree": false,
    "additionalDetails": "N/A"
  },
  {
    "id": "3",
    "category": "ICU",
    "year_required": 7,
    "title": "ICU Nurse",
    "employer": "321",
    "assignTo": null,
    "approve": false,
    "completed": false,
    "location": "Philadelphia, PA",
    "startDate": "2023-08-01",
    "endDate": "2023-08-31",
    "M": false,
    "T": false,
    "W": true,
    "Th": true,
    "F": true,
    "St": true,
    "Sn": false,
    "start": "19:00:00",
    "end": "07:00:00",
    "shiftHour": 12,
    "patient_population": "adults",
    "patient_number": 2,
    "stipend": 3000,
    "weekly_pay": 1200,
    "bonus": 600,
    "contact_person": "Emma White",
    "contact_email": "emma.white@example.com",
    "parkingFree": true,
    "additionalDetails": "This is a night shift position in an ICU unit"
  },
  {
    "id": "4",
    "category": "Psychiatric",
    "year_required": 2,
    "title": "Psychiatric Nurse",
    "employer": "987",
    "assignTo": null,
    "approve": false,
    "completed": false,
    "location": "Boston, MA",
    "startDate": "2023-09-01",
    "endDate": "2023-09-30",
    "M": true,
    "T": false,
    "W": true,
    "Th": false,
    "F": true,
    "St": false,
    "Sn": true,
    "start": "08:30:00",
    "end": "16:30:00",
    "shiftHour": 8,
    "patient_population": "adults",
    "patient_number": 8,
    "stipend": 2500,
    "weekly_pay": 900,
    "bonus": 400,
    "contact_person": "Robert Brown",
    "contact_email": "robert.brown@example.com",
    "parkingFree": false,
    "additionalDetails": "Position in a mental health outpatient clinic"
  }
]


export { people, jobs };
